---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bytezbyb/public_html/
    - /bin/cp index_main.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp -R /media/images/ $DEPLOYPATH